#!/usr/bin/env python3
"""Generate the embedded buff-duration catalog from the eqlwiki spell harvest.

Offline: reads spells.json and writes src/EQBuddy.Core/Data/BuffDurations.json —
the catalog behind buff countdown timers. A buff is any beneficial spell with a
documented duration of a minute or more and a cast-on-you landing line; the
tracker correlates a recent cast with the landing line (the mez pattern), starts
a countdown from the wiki duration, learns real durations from natural fades
(ranks and AAs lengthen them), and clears on the fade line.

Exclusions (each listed in buffs-report.md):
  - landing lines already claimed by SlowSpells.json, FadeMessages.json or the
    regen tick line: exact-match catalogs must partition the message space.
  - durations under 60s: a countdown that expires during its own cast is noise.
  - no cast-on-you message: nothing to anchor the timer to.

Outputs:
  ../../../src/EQBuddy.Core/Data/BuffDurations.json  - the catalog
  buffs-report.md                                    - summary + exclusions
"""

import json
from pathlib import Path

import spellnames

HERE = Path(__file__).resolve().parent
SPELLS = HERE / "spells.json"
FADES = HERE.parents[2] / "src" / "EQBuddy.Core" / "Data" / "FadeMessages.json"
SLOWS = HERE.parents[2] / "src" / "EQBuddy.Core" / "Data" / "SlowSpells.json"
REGENS = HERE.parents[2] / "src" / "EQBuddy.Core" / "Data" / "RegenSpells.json"
OUT = HERE.parents[2] / "src" / "EQBuddy.Core" / "Data" / "BuffDurations.json"
REPORT = HERE / "buffs-report.md"

MIN_DURATION = 60


def beneficial(s) -> bool:
    """Is this a buff we should time?

    The wiki states it outright on most pages. On 200 of 1,929 it says nothing, and
    treating silence as "no" silently dropped real buffs — DeusSilvam could not add
    Talisman of Altuna, Strength, Agility, Dexterity, Stamina or Spirit of the Puma to
    his timers, and all six are on the wiki with durations (#162).

    Simply admitting the blanks would be worse: most of them are debuffs (Asphyxiate,
    Beguile, Bonds of Force), and a debuff in the buff catalog would start a countdown
    on something the player never cast. So a blank must EARN admission on two
    independent signals — the spell targets a friend or yourself, AND the page calls it
    some kind of Buff. Both, because either alone lets something through.
    """
    if s.get("beneficial") is True:
        return True
    if s.get("beneficial") is False:
        return False
    target = (s.get("target_type") or "").lower()
    friendly = "friendly" in target or "group member" in target or target.strip() == "self"
    return friendly and "buff" in (s.get("spell_type_raw") or "").lower()


def canonical(name: str) -> str:
    """See spellnames.py — folds apostrophe styles AND strips the wiki's
    ` (Spell)` / ` (Effect)` page-title disambiguator, which the game never writes."""
    return spellnames.canonical(name)


def main():
    spells = json.loads(SPELLS.read_text(encoding="utf-8"))
    fade_msgs = {e["message"].lower() for e in json.loads(FADES.read_text(encoding="utf-8"))}
    slow_msgs = {m["message"].lower() for m in json.loads(SLOWS.read_text(encoding="utf-8"))["messages"]}
    regen_msg = json.loads(REGENS.read_text(encoding="utf-8"))["message"].lower()
    claimed = fade_msgs | slow_msgs | {regen_msg}

    excluded = []
    by_message = {}
    for s in spells:
        if not beneficial(s):
            continue
        name = canonical(s["name"])
        duration = s.get("duration_seconds") or 0
        msg = (s.get("msg_cast_on_you") or "").strip()
        if duration < MIN_DURATION:
            if duration and msg:
                excluded.append((name, f"duration {duration:0.0f}s < {MIN_DURATION}s"))
            continue
        if not msg:
            excluded.append((name, "no cast-on-you message on the wiki page"))
            continue
        if msg.lower() in claimed:
            excluded.append((name, f"landing line {msg!r} already claimed by another catalog"))
            continue
        group = by_message.setdefault(msg, {})
        old = group.get(name)
        rec = {"name": name, "durationSeconds": duration}
        if old:
            rec["durationSeconds"] = max(rec["durationSeconds"], old["durationSeconds"])
        group[name] = rec

    messages = []
    for msg, group in sorted(by_message.items()):
        cands = sorted(group.values(), key=lambda r: r["name"])
        label = cands[0]["name"] if len(cands) == 1 else None
        messages.append({
            "message": msg,
            "label": label or SharedLabel(msg, cands),
            "spells": cands,
        })

    catalog = {
        "comment": "Buff-duration catalog for buff countdown timers. Grouped by "
                   "cast-on-you landing line; the tracker resolves shared lines via "
                   "cast correlation and treats unresolved durations as estimates. "
                   "Generated by scripts/harvests/eqlwiki/buffs-harvest.py — "
                   "regenerate, never hand-edit. Exclusions in buffs-report.md.",
        "messages": messages,
    }
    OUT.write_text(json.dumps(catalog, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")

    n = sum(len(m["spells"]) for m in messages)
    shared = [m for m in messages if len(m["spells"]) > 1]
    lines = [
        "# Buff-duration catalog report", "",
        f"- {n} buffs across {len(messages)} landing lines ({len(shared)} shared)",
        "", "## Shared landing lines (cast correlation resolves; unresolved = est)", "",
    ]
    for m in sorted(shared, key=lambda m: -len(m["spells"]))[:20]:
        lines.append(f"- {m['message']!r}: {len(m['spells'])} spells")
    lines += ["", "## Excluded", ""]
    for name, reason in sorted(excluded):
        lines.append(f"- {name}: {reason}")
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{n} buffs across {len(messages)} lines -> {OUT.name}")


# Names for landing lines shared by several spells. Echoing the sentence back was the
# old behaviour and it read as EQBuddy quoting the game at you: DeusSilvam's haste timer
# said "You feel much faster" while a single-spell neighbour said "Selo's Accelerating
# Chorus" (#162). Where the spells share a stem the name comes from them; where they do
# not, it is the line's ordinary name. Add one whenever a new shared line appears —
# BuffCatalogLabelTests fails the build if any line falls back to its own message.
SHARED_LINE_NAMES = {
    "You feel charismatic.": "Charisma line",
    "You feel dexterous.": "Dexterity line",
    "You feel protected from magic.": "Magic resist line",
    "You feel the spirit of wolf enter you.": "Spirit of Wolf line",
    "A coat of shimmering runes surround you.": "Rune line",
    "A cool breeze slips through your mind.": "Clarity line",
    "A feeling of temperance washes over you.": "Temperance line",
    "A mystic symbol flashes before your eyes.": "Symbol line",
    "A soft breeze slips through your mind.": "Clarity II line",
    "You are enveloped by flame.": "Fire damage shield",
    "You are now a wolf.": "Wolf form",
    "You are surrounded by a thorny barrier.": "Thorns damage shield",
    "You become like the dead.": "Dead Man Floating",
    "You begin to radiate with divine strength.": "Divine Strength line",
    "You begin to radiate.": "O'Keil's line",
    "You begin to regenerate.": "Regeneration line",
    "You drink the potion.": "Potion",
    "You feel different.": "Illusion",
    "You feel heroic.": "Heroism line",
    "You feel much faster.": "Haste line",
    "You feel no need to breathe.": "Enduring Breath line",
    "You feel stronger.": "Strength line",
    "You feel the favor of the gods upon you.": "Cleric AC line",
    "You feel the skin peel from your bones.": "Lich line",
    "You feel tough.": "Shaman stamina line",
    "You feel your body pulse with energy.": "Augmentation line",
    "You feel your skin tingle.": "Invisibility vs Undead",
    "You have taken root.": "Treeform",
    "You vanish.": "Invisibility line",
    "Your eyes feel stronger.": "Sight line",
    "Your eyes tingle.": "Vision line",
    "Your feet leave the ground.": "Levitation",
    "Your image blurs.": "Blur line",
    "Your mind sharpens.": "Intelligence line",
    "Your skin shimmers.": "Natureskin line",
    "Your skin turns hard as diamond.": "Diamond skin",
    "Your skin turns hard as steel.": "Steel skin",
    "Your skin turns hard as stone.": "Stone skin",
    "Your skin turns hard as wood.": "Wood skin",
    "Your spirit drifts from your body.": "Bind sight line",
    "Your thoughts begin to race and flow faster.": "Gift line",
    # Alchemy potion lines — each shared across the effect's tiers (I..IX).
    "An aura of beneficial awareness surrounds you.": "Benefit Awareness line",
    "An aura of cold awareness surrounds you.": "Cold Awareness line",
    "An aura of disease awareness surrounds you.": "Disease Awareness line",
    "An aura of heat awareness surrounds you.": "Heat Awareness line",
    "An aura of magical awareness surrounds you.": "Magic Awareness line",
    "An aura of poison awareness surrounds you.": "Poison Awareness line",
    "An aura of spiritualism envelops you.": "Spiritualism elixir line",
    "You feel very fast.": "Speed elixir line",
    "Your mind begins to clear.": "Clarity elixir line",
    "Your mind expands.": "Mystical Infusion line",
}


def SharedLabel(msg: str, cands) -> str:
    """A display label for a shared line: its curated name, else the sentence trimmed.
    The fallback is a build failure waiting to happen by design — see the test."""
    return SHARED_LINE_NAMES.get(msg, msg.rstrip(".!"))


if __name__ == "__main__":
    main()
