#!/usr/bin/env python3
"""Generate the embedded debuff-landing catalog from the eqlwiki spell harvest.

Offline: reads spells.json and writes src/EQBuddy.Core/Data/DebuffLandings.json —
the catalog behind "lost as X landed" in the buff-set loss history.

Why it exists (discussion #120, Frankthetankk): BuffLossLog can already blame a
hostile landing for a buff going missing, but the only evidence it had was a named
damage line or a slow. A pure debuff — Malaise drops your strength and AC, does no
damage and is not a slow — landed completely silently, so the buff it displaced was
recorded as merely "faded" with no cause. His documented case (Malaise displacing
Elemental Shield) needs exactly this: the landing line "You feel somewhat vulnerable."
resolved back to a spell name.

Grouped BY MESSAGE, like the slow catalog, because several debuffs share a line and
naming one of them would be a guess.

Exclusions (each listed in debuffs-report.md):
  - messages already claimed by FadeMessages / SlowSpells / BuffDurations /
    RegenSpells: the exact-match catalogs must partition the message space, or a
    line would parse as two different events.
  - spells with no cast-on-you message: nothing to key on.

Outputs:
  ../../../src/EQBuddy.Core/Data/DebuffLandings.json  - the catalog
  debuffs-report.md                                   - summary + exclusions
"""

import json
from pathlib import Path

import spellnames

HERE = Path(__file__).resolve().parent
SPELLS = HERE / "spells.json"
DATA = HERE.parents[2] / "src" / "EQBuddy.Core" / "Data"
OUT = DATA / "DebuffLandings.json"
REPORT = HERE / "debuffs-report.md"


def canonical(name: str) -> str:
    """See spellnames.py — folds apostrophe styles AND strips the wiki's
    ` (Spell)` / ` (Effect)` page-title disambiguator, which the game never writes."""
    return spellnames.canonical(name)


def claimed_messages() -> set:
    claimed = {e["message"].lower()
               for e in json.loads((DATA / "FadeMessages.json").read_text(encoding="utf-8"))}
    claimed |= {m["message"].lower() for m in
                json.loads((DATA / "SlowSpells.json").read_text(encoding="utf-8"))["messages"]}
    claimed |= {m["message"].lower() for m in
                json.loads((DATA / "BuffDurations.json").read_text(encoding="utf-8"))["messages"]}
    claimed.add(json.loads((DATA / "RegenSpells.json").read_text(encoding="utf-8"))["message"].lower())
    return claimed


def main():
    spells = json.loads(SPELLS.read_text(encoding="utf-8"))
    claimed = claimed_messages()

    excluded = []
    by_message = {}
    for s in spells:
        # Only what the wiki states outright. A blank "beneficial" is exactly the
        # ambiguity that let debuffs near the BUFF catalog (#162) — here the risk
        # runs the other way, and a buff mistaken for a debuff would invent a cause
        # for a loss out of the player's own casting. Silence stays out.
        if s.get("beneficial") is not False:
            continue
        name = canonical(s["name"])
        msg = (s.get("msg_cast_on_you") or "").strip()
        if not msg:
            continue
        if msg.lower() in claimed:
            excluded.append((name, f"landing line {msg!r} already claimed by another catalog"))
            continue
        by_message.setdefault(msg, set()).add(name)

    messages = [{"message": msg, "spells": sorted(names)}
                for msg, names in sorted(by_message.items())]

    catalog = {
        "comment": "Detrimental cast-on-you landing lines, message -> candidate spells. "
                   "Used by BuffLossLog to name what displaced a buff. Grouped by "
                   "message because several debuffs share a line; the loss entry shows "
                   "the shared line's candidates rather than guessing one. Generated by "
                   "scripts/harvests/eqlwiki/debuffs-harvest.py - regenerate, never "
                   "hand-edit. Exclusions in debuffs-report.md.",
        "messages": messages,
    }
    OUT.write_text(json.dumps(catalog, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")

    shared = [m for m in messages if len(m["spells"]) > 1]
    lines = [
        "# Debuff-landing catalog report", "",
        f"- {sum(len(m['spells']) for m in messages)} debuffs across "
        f"{len(messages)} landing lines ({len(shared)} shared)", "",
        "## Shared landing lines (the loss entry names the line, not one spell)", "",
    ]
    for m in sorted(shared, key=lambda m: -len(m["spells"]))[:20]:
        lines.append(f"- {m['message']!r}: {', '.join(m['spells'])}")
    lines += ["", "## Excluded", ""]
    for name, reason in sorted(set(excluded)):
        lines.append(f"- {name}: {reason}")
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"{sum(len(m['spells']) for m in messages)} debuffs across "
          f"{len(messages)} lines -> DebuffLandings.json")


if __name__ == "__main__":
    main()
