#!/usr/bin/env python3
"""Compare the spawn catalog's MEASURED respawn timers against eqlwiki (PR 0 of the
"verified spawn-timer feed" plan, Fable 5 2026-08-22; David's direction: eqlwiki is the
SOURCE, and EQBuddy is the tool that helps it update).

Scope, deliberately narrow: only catalog entries carrying `trusted: true` — the ones
MEASURED from family logs (Befallen's zone clock, Crushbone's trainers), which is the
"what we already know that the wiki does not" David was pointing at. For each, read the
creature page's `respawn_time` field and report one of:

  MISSING     the page has no respawn_time -> a paste-ready line for a human
  DISAGREES   the page says something else -> both values, for a human to reconcile
  AGREES      nothing to do (listed so the report's coverage is visible)
  NO PAGE     the creature has no wiki page at all

**Flags only, like the rest of the refresh: this writes a REPORT (respawn-report.md),
never a catalog and never a wiki edit.** The player-facing half (the pack's respawn
section, fed by an observation ledger) is PR 1-2 of the same plan; this script needs no
player evidence and can run today.

Usage: python respawn-diff.py [--refetch]
"""
import json
import re
import sys
import time
import urllib.parse
import urllib.request
from hashlib import md5
from pathlib import Path

HERE = Path(__file__).resolve().parent
CACHE = HERE / "cache"
API = "https://eqlwiki.com/api.php"
UA = "EQBuddy-harvester/1.0 (contact: david.edwards08@gmail.com; polite ~1 req/sec)"
CATALOG = HERE.parents[2] / "src" / "EQBuddy.Core" / "Data" / "SpawnCatalog.json"
REPORT = HERE / "respawn-report.md"


def api_get(params: dict) -> dict:
    params = dict(params, format="json", formatversion="2")
    url = API + "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        data = json.load(resp)
    time.sleep(1.1)  # polite pacing (consequence-list 7: request rates at eqlwiki)
    return data


def fetch_wikitext(title: str, refetch: bool) -> tuple[str | None, str | None]:
    """(served_title, wikitext) — the SERVED title, never the requested one (trap 3)."""
    CACHE.mkdir(exist_ok=True)
    key = f"{title}.{md5(title.encode()).hexdigest()[:8]}.wikitext"
    cache_file = CACHE / key
    if cache_file.exists() and not refetch:
        text = cache_file.read_text(encoding="utf-8")
        first, _, rest = text.partition("\n")
        return (first.removeprefix("#title:") or title, rest) if first.startswith("#title:") \
            else (title, text)
    data = api_get({
        "action": "query", "prop": "revisions", "titles": title, "redirects": 1,
        "rvprop": "content", "rvslots": "main",
    })
    pages = data.get("query", {}).get("pages", [])
    if not pages or pages[0].get("missing"):
        cache_file.write_text("#title:\n", encoding="utf-8")
        return None, None
    served = pages[0]["title"]
    text = pages[0]["revisions"][0]["slots"]["main"]["content"]
    cache_file.write_text(f"#title:{served}\n{text}", encoding="utf-8")
    return served, text


def respawn_field(wikitext: str) -> str | None:
    """The raw respawn_time value, or None when the field is absent. The field is
    free text in the wiki's own idiom ("9.5 min", "Triggered", "3 days with 12 hour
    variance") — never parsed into seconds here; a human reconciles."""
    m = re.search(r"^\s*\|\s*respawn_time\s*=\s*(.*?)\s*$", wikitext, re.MULTILINE)
    if not m:
        return None
    return m.group(1) or ""


def wiki_wording(seconds: int) -> str:
    """The catalog's measured value in the wiki's own idiom, for the paste line."""
    if seconds % 3600 == 0 and seconds >= 3600:
        h = seconds // 3600
        return f"{h} hour{'s' if h != 1 else ''}"
    minutes = seconds / 60
    return f"{minutes:g} min"


def main() -> int:
    refetch = "--refetch" in sys.argv
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))

    trusted = []
    for zone in catalog["zones"]:
        for named in zone.get("named", []):
            if named.get("trusted") and named.get("respawnSeconds"):
                trusted.append((zone["zone"], named))

    lines = [
        "# Trusted respawn timers vs eqlwiki",
        "",
        "Generated by `respawn-diff.py` — flags only, nothing is written to the wiki or",
        "the catalog. Every entry below was MEASURED from a family log (`trusted: true`),",
        "which is what makes it worth offering to the shared reference. A human opens the",
        "edit link, pastes, reviews and saves — the same contract as the contribution pack.",
        "",
        f"Catalog: {len(trusted)} trusted entr{'ies' if len(trusted) != 1 else 'y'}.",
        "",
    ]

    counts = {"MISSING": 0, "DISAGREES": 0, "AGREES": 0, "NO PAGE": 0}
    for zone_name, named in trusted:
        name = named["name"]
        seconds = named["respawnSeconds"]
        ours = wiki_wording(seconds)
        served, text = fetch_wikitext(name, refetch)
        if text is None:
            counts["NO PAGE"] += 1
            lines += [
                f"## {name} ({zone_name}) — NO PAGE",
                f"Measured: {ours} ({seconds}s). The creature has no wiki page; the",
                "contribution pack's new-page skeleton is the right vehicle, not this diff.",
                "",
            ]
            continue
        field = respawn_field(text)
        edit = ("https://eqlwiki.com/index.php?title="
                + urllib.parse.quote((served or name).replace(" ", "_")) + "&action=edit")
        if field is None or field == "":
            counts["MISSING"] += 1
            lines += [
                f"## {name} ({zone_name}) — MISSING on the wiki",
                f"Measured: {ours} ({seconds}s"
                + (f", note: {named['note'][:120]}" if named.get("note") else "") + ")",
                f"Edit: {edit}",
                "Paste into the {{Namedmobpage}} template"
                + (" (the field is empty)" if field == "" else " (add the field)") + ":",
                "```",
                f"| respawn_time  = {ours}",
                "```",
                "",
            ]
        elif _normalise(field) == _normalise(ours):
            counts["AGREES"] += 1
            lines += [f"## {name} ({zone_name}) — AGREES ({field!r})", ""]
        else:
            counts["DISAGREES"] += 1
            lines += [
                f"## {name} ({zone_name}) — DISAGREES",
                f"Wiki says: {field!r} · we measured: {ours} ({seconds}s). Compare, don't",
                "overwrite — the wiki may carry a range or a tier our sample hasn't seen.",
                f"Edit: {edit}",
                "",
            ]

    lines += [
        "---",
        "",
        "Totals: " + " · ".join(f"{k}: {v}" for k, v in counts.items()),
        "",
    ]
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {REPORT.name}: " + " · ".join(f"{k}={v}" for k, v in counts.items()))
    return 0


def _normalise(s: str) -> str:
    return re.sub(r"[^a-z0-9.]", "", s.lower()).replace("minutes", "min").replace("mins", "min")


if __name__ == "__main__":
    sys.exit(main())
