using System.Reflection;
using System.Text.Json;

namespace EQBuddy.Core;

/// <summary>Buff landing lines ("You feel the favor of the gods upon you.") mapped to
/// candidate spells with wiki durations — the catalog behind buff countdown timers.
/// Generated by scripts/harvests/eqlwiki/buffs-harvest.py.</summary>
public sealed class BuffDurationCatalog
{
    public sealed class BuffSpell
    {
        public string Name { get; set; } = "";
        public double DurationSeconds { get; set; }
    }

    public sealed class Entry
    {
        public string Message { get; set; } = "";
        public string Label { get; set; } = "";
        public BuffSpell[] Spells { get; set; } = [];
    }

    private sealed class Root { public List<Entry> Messages { get; set; } = []; }

    private readonly Dictionary<string, Entry> _byMessage;
    private readonly HashSet<string> _spellNames;

    public BuffDurationCatalog(IEnumerable<Entry> entries)
    {
        _byMessage = entries.Where(e => e.Message.Length > 0 && e.Spells.Length > 0)
            .ToDictionary(e => e.Message, e => e, StringComparer.OrdinalIgnoreCase);
        _spellNames = _byMessage.Values.SelectMany(e => e.Spells.Select(s => s.Name))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
    }

    public int Count => _byMessage.Count;
    public Entry? Find(string message) => _byMessage.TryGetValue(message, out var e) ? e : null;
    public bool IsBuffSpell(string spell) => _spellNames.Contains(SpellCatalog.BaseName(spell));

    /// <summary>Every spell whose landing line the catalog can attribute — the buff-set
    /// editor's search space (#120). Restricting set entries to these keeps the set
    /// honest: a spell whose landing we can't recognize would read "not seen" forever.</summary>
    public IReadOnlyCollection<string> SpellNames => _spellNames;

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    public static BuffDurationCatalog LoadEmbedded()
    {
        using var stream = Assembly.GetExecutingAssembly()
            .GetManifestResourceStream("EQBuddy.Core.Data.BuffDurations.json")
            ?? throw new InvalidOperationException("BuffDurations.json missing from resources");
        var root = JsonSerializer.Deserialize<Root>(stream, JsonOpts)
            ?? throw new InvalidOperationException("BuffDurations.json unreadable");
        return new BuffDurationCatalog(root.Messages);
    }

    public static BuffDurationCatalog Default { get; } = LoadEmbedded();
}

/// <summary>A buff currently believed active on YOU. Estimated means the duration is
/// the wiki base for an unresolved candidate set (or the longest of them) — ranks and
/// AAs lengthen buffs, so the countdown is labeled est until a natural fade teaches
/// the character's real number.</summary>
public sealed record BuffState(
    string Label, string[] Candidates, string Caster,
    DateTime LandedAt, DateTime? ExpiresAt, bool Estimated)
{
    public double? RemainingSeconds(DateTime now) =>
        ExpiresAt is { } e ? Math.Max(0, (e - now).TotalSeconds) : null;

    /// <summary>
    /// The landing's FULL candidate set, kept only when a `/outputfile spellbook` dump
    /// narrowed <see cref="Candidates"/> — empty otherwise, which is every buff the log
    /// alone accounted for.
    ///
    /// **One property rather than three, on purpose.** It answers "did the dump decide
    /// this" (<see cref="DumpNarrowed"/>) and "what may a fade line call it"
    /// (<see cref="FadeNames"/>) from a single stored fact; two fields agreeing about one
    /// event is trap 4, and these two questions are only ever asked together.
    /// </summary>
    public string[] NarrowedFrom { get; init; } = [];

    /// <summary>A spellbook dump — not the log — decided which candidates stand. Blocks
    /// fade-teaching: <see cref="BuffTracker"/> learns a real duration only from a landing
    /// the LOG resolved, and a dump-narrowed set of one is not that. Without this gate the
    /// spellbook would become a timer source through the back door, which is exactly the
    /// thing the owner lock rules out.</summary>
    public bool DumpNarrowed => NarrowedFrom.Length > 0;

    /// <summary>Every name a fade line may use for this buff. **The dump must never cost
    /// us a fade**: narrowing to "Rune V" and then meeting a "Rune IV" fade line would
    /// leave the chip hanging until its linger expired, which is a stale spellbook
    /// erasing something the log plainly said. Fades match the wider set; only the
    /// countdown and the tooltip use the narrower one.</summary>
    public string[] FadeNames => DumpNarrowed ? NarrowedFrom : Candidates;
}

/// <summary>
/// Tracks beneficial buffs on the player, the same consumer shape as
/// <see cref="MezTracker"/>: cast lines arm a short window, the cast-on-you line
/// inside it starts the countdown, the fade line ends it — and a natural fade whose
/// landing was cleanly attributed teaches the spell's REAL duration for this
/// character (ranks and AAs lengthen buffs; the wiki base is a floor, so learned
/// values only ever ratchet the countdown up, tick-floored). Zoning keeps buffs —
/// they survive it in game; dying does not.
/// </summary>
public sealed class BuffTracker
{
    public static readonly TimeSpan CastToLand = TimeSpan.FromSeconds(8);
    /// <summary>Past its expiry a chip lingers at 0:00 — an estimated duration is a
    /// floor (ranks lengthen), so vanishing exactly on time would often be a lie.
    /// The fade line is the real end and clears it whenever it comes.</summary>
    public static readonly TimeSpan ExpiryLinger = TimeSpan.FromMinutes(5);
    public const double ServerTickSeconds = 6;

    private readonly BuffDurationCatalog _catalog;
    private readonly Dictionary<string, double> _learned = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, BuffState> _active = new(StringComparer.OrdinalIgnoreCase);
    // Session-seen evidence behind the buff set's honesty states (#120). These answer
    // "did THIS session's log ever show it", not "is it up" — so death and zoning
    // never clear them, and an unresolved landing marks its WHOLE candidate set seen
    // (the same identity treatment the tracker gives the active entry itself).
    private readonly HashSet<string> _seenLandings = new(StringComparer.OrdinalIgnoreCase);
    private readonly HashSet<string> _seenFades = new(StringComparer.OrdinalIgnoreCase);
    private readonly HashSet<string> _seenOwnCasts = new(StringComparer.OrdinalIgnoreCase);
    private readonly List<(string Caster, string Spell, DateTime Time)> _recentCasts = [];
    private readonly Dictionary<string, DateTime> _lastCastOf = new(StringComparer.OrdinalIgnoreCase);
    private string? _storePath;
    private readonly object _lock = new();

    public event Action? Changed;

    /// <summary>The player's Spell Casting Reinforcement rank (0–4), from the AA
    /// ledger: +5/15/30/50% duration on beneficial spells YOU cast. Applied to the
    /// wiki-base estimate only — a learned duration already includes the character's
    /// real extensions, and applying it twice would overshoot every countdown.</summary>
    public Func<int>? ReinforcementRank { get; set; }

    private static readonly double[] ReinforcementBonus = [0, 0.05, 0.15, 0.30, 0.50];

    public BuffTracker(BuffDurationCatalog? catalog = null) =>
        _catalog = catalog ?? BuffDurationCatalog.Default;

    // ---- the optional spellbook (OE-5 LOCK A) -----------------------------------

    private SpellbookFile.Snapshot? _spellbook;
    private string? _spellbookFolder;
    private string _spellbookCharacter = "";

    /// <summary>
    /// Point the tracker at this character's `/outputfile spellbook` dump, if there is
    /// one. Optional in every sense: a character who has never run the command, a folder
    /// that does not exist and an unreadable file all leave the tracker doing exactly what
    /// it did before this existed.
    ///
    /// <see cref="LogWatcher.Select"/> calls it, because Select is the one place that
    /// knows both the log folder and the character — the same moment it resets the
    /// session for the newly selected log. The folder and character are remembered so a
    /// `/outputfile spellbook` run mid-session can re-read on its own announcement.
    /// </summary>
    public void AttachSpellbook(string? logFolder, string character)
    {
        _spellbookFolder = logFolder;
        _spellbookCharacter = character ?? "";
        ReloadSpellbook();
    }

    /// <summary>What the attached dump said, or null when there is none. For tests and for
    /// anything that wants to report the dump's age; nothing in the tracker's own path
    /// needs it.</summary>
    public SpellbookFile.Snapshot? Spellbook
    {
        get { lock (_lock) return _spellbook; }
    }

    /// <summary>Read the dump for the attached character. File I/O deliberately OUTSIDE
    /// the lock — the ingest thread calls this from <see cref="Apply"/> when a dump is
    /// announced, and a slow disk must not stall a landing.</summary>
    private void ReloadSpellbook()
    {
        if (_spellbookCharacter.Length == 0) { lock (_lock) _spellbook = null; return; }
        var book = SpellbookFile.FindLatest(_spellbookFolder, _spellbookCharacter);
        lock (_lock) _spellbook = book;
    }

    /// <summary>Learned durations persist per character (mez-store pattern).</summary>
    public void AttachStore(string path)
    {
        _storePath = path;
        try
        {
            if (!File.Exists(path)) return;
            var stored = JsonSerializer.Deserialize<Dictionary<string, double>>(File.ReadAllText(path));
            if (stored is null) return;
            lock (_lock)
                foreach (var (spell, seconds) in stored)
                    if (seconds is > 0 and < 4 * 3600) _learned.TryAdd(spell, seconds);
        }
        catch { /* corrupt store: rewritten on next learn */ }
    }

    public void Apply(GameEvent evt)
    {
        // The dump's own announcement, read here on the ingest thread the same way the
        // quest reconcile reads the inventory one (#241): running /outputfile spellbook
        // mid-session sharpens the NEXT landing rather than the next launch. Outside the
        // lock, because it is file I/O and it opens no buff state.
        if (evt is OutputfileEvent dump
            && OutputfileAutoImport.KindOf(dump.FileName) == OutputfileKind.Spellbook)
            ReloadSpellbook();

        var changed = false;
        lock (_lock)
        {
            switch (evt)
            {
                case SpellCastEvent own when _catalog.IsBuffSpell(own.Spell):
                    Remember("You", own.Spell, own.Time);
                    _seenOwnCasts.Add(SpellCatalog.BaseName(own.Spell));
                    break;
                case OtherCastEvent other when _catalog.IsBuffSpell(other.Spell):
                    Remember(other.Caster, other.Spell, other.Time);
                    break;

                case BuffLandedEvent landed when _catalog.Find(landed.Message) is { } entry:
                    changed = OnLanding(entry, landed.Time);
                    break;

                // A blocked cast never lands, so no state opens (landing lines are the
                // only thing that opens state) — but its cast must not stay remembered:
                // armed for up to CastToLand, it would resolve a LATER unexplained
                // landing of the same message (a groupmate's cast, a clicky) to OUR
                // cast and caster. Only "You" disarms — the line is first-person.
                case SpellBlockedEvent blocked:
                    _recentCasts.RemoveAll(c => c.Caster == "You"
                        && SpellCatalog.BaseName(c.Spell).Equals(
                            SpellCatalog.BaseName(blocked.Spell), StringComparison.OrdinalIgnoreCase));
                    break;

                case BuffFadeEvent fade:
                    // Even a fade with no active match is evidence (#120): the log
                    // opened mid-session, the buff WAS up, and now it's gone.
                    foreach (var s in fade.Spells.Where(_catalog.IsBuffSpell))
                        _seenFades.Add(SpellCatalog.BaseName(s));
                    changed = OnFade(fade.Spells, fade.Time);
                    break;
                // "Your X spell has worn off." with no target names YOUR buff ending.
                case SpellWornOffEvent { Pet: false, Target.Length: 0 } worn
                    when _catalog.IsBuffSpell(worn.Spell):
                    _seenFades.Add(SpellCatalog.BaseName(worn.Spell));
                    changed = OnFade([worn.Spell], worn.Time);
                    break;

                case DeathEvent:
                    changed = _active.Count > 0;
                    _active.Clear();
                    break;
                    // ZoneEvent deliberately absent: buffs survive zoning.
            }
            _recentCasts.RemoveAll(c => evt.Time - c.Time > CastToLand);
            foreach (var (key, b) in _active.Where(kv =>
                         kv.Value.ExpiresAt is { } e && evt.Time - e > ExpiryLinger).ToList())
            {
                _active.Remove(key);
                changed = true;
            }
        }
        if (changed) Changed?.Invoke();
    }

    private void Remember(string caster, string spell, DateTime t)
    {
        _recentCasts.Add((caster, spell, t));
        if (_recentCasts.Count > 32) _recentCasts.RemoveRange(0, 16);
        _lastCastOf[SpellCatalog.BaseName(spell)] = t;
    }

    private bool OnLanding(BuffDurationCatalog.Entry entry, DateTime time)
    {
        // A recent cast of a candidate names the spell exactly (and its caster);
        // without one — a clicky, a stranger out of range — every candidate stands,
        // the longest duration wins, and the chip says est.
        var cast = _recentCasts.LastOrDefault(c => time - c.Time <= CastToLand
            && entry.Spells.Any(s => s.Name.Equals(SpellCatalog.BaseName(c.Spell), StringComparison.OrdinalIgnoreCase)));
        var resolved = cast.Spell is { Length: > 0 };
        var label = resolved ? SpellCatalog.BaseName(cast.Spell) : entry.Label;
        var candidates = resolved ? new[] { label } : entry.Spells.Select(s => s.Name).ToArray();

        // THE DUMP ONLY EVER SPEAKS WHERE THE LOG DID NOT. A cast line names the spell and
        // its caster outright, so a resolved landing is untouched here — including one the
        // spellbook does not list, which is a stale dump and not a wrong log.
        var narrowedFrom = Array.Empty<string>();
        if (!resolved && NarrowBySpellbook(candidates) is { } narrowed)
        {
            narrowedFrom = candidates;
            candidates = narrowed;
        }

        var baseSeconds = resolved
            ? entry.Spells.First(s => s.Name.Equals(label, StringComparison.OrdinalIgnoreCase)).DurationSeconds
            // The longest of what is STILL standing. Narrowing "Rune IV or Rune V" down to
            // the rank this character has scribed is the whole accuracy win: the estimate
            // stops being the longest rank in the game and becomes the longest rank you own.
            : entry.Spells.Where(s => candidates.Contains(s.Name, StringComparer.OrdinalIgnoreCase))
                .Max(s => s.DurationSeconds);
        // Your own cast gets your Spell Casting Reinforcement applied to the estimate;
        // someone else's caster AAs are invisible to your log, so their base stands.
        if (resolved && cast.Caster == "You"
            && ReinforcementRank?.Invoke() is > 0 and <= 4 and var rank)
            baseSeconds *= 1 + ReinforcementBonus[rank];
        var learned = resolved && _learned.TryGetValue(label, out var known) ? known : (double?)null;
        var estimated = !resolved || learned is null;

        _active[label] = new BuffState(label, candidates, resolved ? cast.Caster : "",
            time, time.AddSeconds(learned ?? baseSeconds), estimated)
        {
            NarrowedFrom = narrowedFrom,
        };
        _seenLandings.Add(SpellCatalog.BaseName(label));
        // The sights are the LOG's claim about what this session showed (#120's honesty
        // states), so they mark the whole landing — a dump that narrowed the countdown has
        // not made the other candidates un-seen.
        foreach (var c in narrowedFrom.Length > 0 ? narrowedFrom : candidates)
            _seenLandings.Add(SpellCatalog.BaseName(c));
        return true;
    }

    /// <summary>
    /// The candidates this character has actually scribed, or null when the dump narrows
    /// nothing — no spellbook attached, or one that recognises none of them.
    ///
    /// **A dump that knows none of the candidates narrows NOTHING, and that is the load
    /// bearing line.** A spellbook written before the character learned the spell, a
    /// clicky item, a rank spelled some way this dump does not use — every one of those is
    /// a reason the log is right and the dump is behind, and none of them is a reason to
    /// shrink a landing the log observed. Returning the whole set unchanged is what "the
    /// log outranks the dump" means in code.
    ///
    /// Two tiers, in this order. **Exact** first, because that is the match that buys a
    /// per-rank duration — `BuffDurations.json` carries "Rune IV" at 5,400s beside "Rune V"
    /// at 6,600s. **Line** (rank-folded) second, so a dump that writes its ranks in a shape
    /// we have not seen still separates two DIFFERENT spells sharing one landing message
    /// (Boon of the Clear Mind vs Clarity) instead of giving up.
    /// </summary>
    private string[]? NarrowBySpellbook(string[] candidates)
    {
        if (candidates.Length < 2) return null;
        SpellbookFile.Snapshot? book;
        lock (_lock) book = _spellbook;
        if (book is null) return null;

        var exact = candidates.Where(book.Knows).ToArray();
        if (exact.Length > 0) return exact.Length < candidates.Length ? exact : null;
        var line = candidates.Where(book.KnowsLine).ToArray();
        return line.Length > 0 && line.Length < candidates.Length ? line : null;
    }

    private bool OnFade(string[] spells, DateTime time)
    {
        // FadeNames, not Candidates: where a spellbook narrowed the set, the fade line may
        // still name a candidate the dump ruled out, and dropping the match would leave a
        // chip hanging that the log had plainly ended. The dump never costs us a fade.
        var doomed = _active.Values.Where(b =>
            b.FadeNames.Intersect(spells, StringComparer.OrdinalIgnoreCase).Any()).ToList();
        foreach (var b in doomed)
        {
            _active.Remove(b.Label);
            // Learning (mez rules, buff flavor): only a cleanly resolved single-spell
            // landing measures anything; a re-cast since landing means this fade may
            // span a chain; and ranks only LENGTHEN, so an observation short of the
            // current belief is a dispel or a click-off, not a duration.
            //
            // `DumpNarrowed` is the second half of that first clause, and it is the gate
            // that keeps the spellbook out of the timer. A set of one used to mean "the
            // LOG named this spell"; a dump can now produce one too, and teaching a real
            // per-character duration off a dump-guessed identity is precisely the
            // back-door the owner lock forbids. Learned durations stay log-taught.
            if (b.Candidates.Length != 1 || b.DumpNarrowed) continue;
            var spell = b.Candidates[0];
            if (_lastCastOf.TryGetValue(spell, out var lastCast) && lastCast > b.LandedAt.AddSeconds(1))
                continue;
            var observed = Math.Floor((time - b.LandedAt).TotalSeconds / ServerTickSeconds) * ServerTickSeconds;
            var floor = b.ExpiresAt is { } e ? (e - b.LandedAt).TotalSeconds : 0;
            if (observed >= floor && observed is > 30 and < 4 * 3600
                && (!_learned.TryGetValue(spell, out var known) || Math.Abs(observed - known) > 0.5))
            {
                _learned[spell] = observed;
                SaveStore();
            }
        }
        return doomed.Count > 0;
    }

    /// <summary>Cheap count for headers and per-tick gates — no list, no sort.</summary>
    public int ActiveCount
    {
        get { lock (_lock) return _active.Count; }
    }

    /// <summary>Active buffs, soonest to fade first; expired entries hold at 0:00
    /// until their fade line or the linger cap (estimates are floors, not facts).</summary>
    public List<BuffState> Snapshot(DateTime now)
    {
        lock (_lock)
            return _active.Values
                .OrderBy(b => b.ExpiresAt ?? DateTime.MaxValue)
                .ToList();
    }

    public IReadOnlyDictionary<string, double> LearnedDurations
    {
        get { lock (_lock) return new Dictionary<string, double>(_learned); }
    }

    /// <summary>What this session's log has shown about buff identities, for the buff
    /// set's honesty states (#120): spells seen landing on you (a landing's whole
    /// candidate set counts), spells seen fading (with or without a matching landing),
    /// and buff spells YOU were seen casting (the set editor's seen-first ranking).
    /// Copies — safe to hold across the tracker's own updates.</summary>
    public BuffSetSights SetSights()
    {
        lock (_lock)
            return new BuffSetSights(
                new HashSet<string>(_seenLandings, StringComparer.OrdinalIgnoreCase),
                new HashSet<string>(_seenFades, StringComparer.OrdinalIgnoreCase),
                new HashSet<string>(_seenOwnCasts, StringComparer.OrdinalIgnoreCase));
    }

    /// <summary>Log-switch reset (stage 2's fix for a stage-1 flag): active buffs and
    /// session sights were process-lifetime, so character A's landings leaked into
    /// character B's Missing/NotSeen claims after a switch. LogWatcher.Select calls
    /// this alongside the stats reset; the newly selected log is then replayed in
    /// full, which re-derives everything that belongs to the new character. Learned
    /// durations stay — their store is install-wide, not session evidence.</summary>
    public void ResetSession()
    {
        lock (_lock)
        {
            _active.Clear();
            _recentCasts.Clear();
            _lastCastOf.Clear();
            _seenLandings.Clear();
            _seenFades.Clear();
            _seenOwnCasts.Clear();
        }
        Changed?.Invoke();
    }

    private int _savePending;

    /// <summary>Debounced like StackingLedgerStore.Save (perf audit #13, the #3
    /// idiom): SaveStore is called under this tracker's lock on the ingest path —
    /// the synchronous write stalled tailing whenever a fade taught a duration.
    /// Flag now, one write ~2 s later; hosts call <see cref="Flush"/> at exit.
    /// Callers hold _lock.</summary>
    private void SaveStore()
    {
        if (_storePath is null) return;
        if (Interlocked.Exchange(ref _savePending, 1) == 1) return;
        Task.Run(async () =>
        {
            await Task.Delay(TimeSpan.FromSeconds(2)).ConfigureAwait(false);
            Interlocked.Exchange(ref _savePending, 0);
            Flush();
        });
    }

    /// <summary>Write now — hosts call this at exit. Serializes under the lock,
    /// writes outside it.</summary>
    public void Flush()
    {
        if (_storePath is not { } path) return;
        try
        {
            string json;
            lock (_lock) json = JsonSerializer.Serialize(_learned);
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, json);
        }
        catch { /* best-effort */ }
    }
}
